### ISSUE TITLE
Re-implement new features for REVM

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#799]
**Changes to `forge run`**

- [x] Configurable artifact types (#762) (fixed by rebase)
- [x] Using new `ethers-solc` functions (#776) (fixed by rebase)

**Changes to the test runners**

- [x] Test result streaming (#798) (fixed by rebase)

**Changes to the fuzzer**
- [ ] Invariant tests (#849)
- [ ] Fuzz dictionary (#731)

**Changes to gas reports**
- [ ] Exporting (#887)

**Changes to cheatcodes**
- [x] `cheats.ffi` (#904)
- [x] `cheats.getCode` (#903)

**Comment by onbjerg** [comment]
Remaining items will be new PRs
