### ISSUE TITLE
Meta: Debugger improvements

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#927]
**Decoding/display**
- [ ] Guidance on how to debug failed tests in the CLI output
- [ ] Visual clues that a precompile is being called (requires more thought, see #916)
- [ ] Showing current values of variables (https://github.com/gakonst/foundry/issues/410)

**Quality of life**
- [ ] Greying out of zero values in memory (https://github.com/gakonst/foundry/issues/902)

**Control flow**
- [ ] Breakpoints

**Capabilities**
- [ ] Debugging functions with parameters (e.g. fuzz tests)
- [ ] Debugging of constructors

**Comment by onbjerg** [comment]
Idea for an interactive debugger: some `Debugger` struct that handles state/displays UI. Messages are passed between the `Debugger` and the debug inspector. Contracts are identified on the fly when the EVM switches context using any number of identifiers

**Comment by henry-hz** [comment]
@onbjerg supose I want to debug the function in the test below called `symbol()`. Using the `forge test --debug symbol` I have to jump a looootttt until I find it. What would be needed to jump directly to my function using the debugger ? I have the impression that using the function signature `0x95d89b41` as an input we could just search it and jump the counter to there. Makes sense ? Is there anyone writing it ?

(I am using the [foundry-huff](https://github.com/huff-language/foundry-huff))

```solidity
    function testSymbol() public {
        string memory r = token.symbol();
        string memory n = 'JHX';
        assertEq(n,r);
    }
```

```assembly
#define macro SYMBOL() = takes (0) returns (0) {
    0x20 0x00 mstore
    [META_SYMBOL_LENGTH] 0x20 mstore
    [META_SYMBOL] 0x40 mstore
    0x60 0x00 return
}
```

**Comment by mds1** [comment]
@henry-hz You can se [`vm.breakpoint`](https://book.getfoundry.sh/cheatcodes/breakpoint#breakpoint)

**Comment by Inphi** [comment]
To add to this, it'll be awesome to have a vim-styled "command mode" that supercedes navigation shortcuts. Though it'll be nice to have a full-blown lua scripting engine to interface with during debugging, it'll be a huge improvement to simply have basic commands;
- `:mem <pos>`, `mems <slot>` given either a slot position or index, print or snap to and highlight that specific memory location
- `:store <addr>` similar operations to inspect specific storage slots
- `:continue <pc>` - fast-forward until execution reaches a specific pc on the current contract. More ergonomic than using `vm.breakpoint` imo as you don't need to rebuild contracts to add new breakpoints.
- A way to scroll the source map display so users can easily see the pc that maps to a given line number in code.

A command-based debug flow would be a good way to introduce feature experiments without cluttering the existing interface.

**Comment by iFrostizz** [comment]
@Inphi Agree, but why would we need to write a lua interface if it can be integrated in the `Tui` directly ?

**Comment by Inphi** [comment]
Lua interface is to write (inline) scripts for faster debugging. Kind of like gdb scripts.

**Comment by zerosnacks** [comment]
From https://github.com/foundry-rs/foundry/issues/4440#issue-1601444539

The debugger should be interactive to allow for collapsing traces, show/hiding more information, etc. Tenderly debugger/trace [UX](https://twitter.com/TenderlyApp/status/1623679228884447234) is very nice IMO so is a good source of inspiration. More info coming soon, need to link existing issues here

(...) 

For example, you can imagine the debugger config looking something like this (made up type names within the Options):

```rust
struct DebuggerConfig {
  trace: Option<CallTrace>,
  opcodes: Option<Vec<Opcodes>>,
  memory_states: Option<Vec<Memory>>,
  stack_states: Option<Vec<Stack>>,
  srcmap: Option<SrcMap>,
}
```

where "trace view" simply has `None` everywhere except for `trace`, while debugger mode may have everything enabled. Users could toggle each config option on/off in the debugger UI.

**Comment by zerosnacks** [comment]
From #5553:

- Making it smarter about where solidity structs are laid out and labelling them with variable names
- visual storage/memory explorer with struct/variable knowledge
- calling convention/ABI.encode awareness
- get better at not losing where it is with weird assembly/reentrancy

**Comment by legion2002** [comment]
* It would be nice to have a pane to look at the storage of the current contract. Since storage can be large, it would be nice to query values by the slot number.
* We also have TSTORE now, so we could also have a transient storage pane.
* For some reason setting breakpoints in the source code didn't work for me, breakpoints in tests work fine.
* Any way to set a breakpoint within an assembly block? Probably not possible, but If the assembly block is large, then you have to scroll through a lot of opcodes to reach the point you care about.
* Also ability to query words at different calldata and memory offsets without scrolling through the relevant panes.
It would be amazing UX  if I could type a command like - :0x20 --memory/calldata/storage/transient
And just get the value at that slot.
